name: Project Board Event Trigger

on:
  project_v2_item:
    types: [created, edited, deleted]

jobs:
  log_event:
    runs-on: ubuntu-latest
    steps:
      - name: Log Event Details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
